### ISSUE TITLE
Résoudre le problème de bouton "Back"

### ISSUE THREAD

**Issue by antoineauger** [etiik37/amra_groupe3#4]
Régler le bon titre et faire disparaître ce F*****\* bouton back

**Comment by etiik37** [comment]
Problème avec le merge, dans la branch Merge, sur ton back button

Si on vas dans probleme solving, et qu'on clique un de ces bouton après, j'pense que tu reste bloqué dedans, du coup, ca bug une fois que tu retourne dans cette branche, c'est assez zarb.
